apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-storage
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
