apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    test: https
spec:
  selector:
    matchLabels:
      app: mysql
      test: https
  template:
    metadata:
      labels:
        app: mysql
        test: https
    spec:
      containers:
      - name: mysql
        image: vrushyash/mariadb:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "50m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mysql123"
          - name: MYSQL_DATABASE
            value: "testDB"
          - name: MYSQL_USER
            value: "vrushal"
          - name: MYSQL_PASSWORD
            value: "mysql123"
        volumeMounts:
          - name: mysql-db-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-db-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim