apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  volumeName: mysql-db-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
